version: "3"
services:
  apache2:
    build: ./php74-apache2
    ports:
    - "80:80"
    volumes:
    - ./html:/var/www/html
    - ./sites-enabled:/etc/apache2/sites-enabled
    - ./log:/var/log/apache2
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=wordpress
    ports:
    - "3306:3306"
    volumes:
    - ./mysql:/var/lib/mysql
  redis:
    image: docker.io/redis
    ports:
    - "6379:6379"
